name: Setup Terragrunt Action
description: Setup the Terragrunt on the path
inputs:
  version:
    description: Version of Terragrunt to install
    required: false
    default: 'latest'
outputs:
  version:
    description: The version on the path
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Setup path
      id: paths
      shell: bash
      run:  |
        mkdir -p "$RUNNER_TEMP/terragrunt-bin"
        echo "$RUNNER_TEMP/terragrunt-bin" >> "$GITHUB_PATH"
        echo "terragrunt-bin=$RUNNER_TEMP/terragrunt-bin" >> "$GITHUB_OUTPUT"
    - name: Load cached Terragrunt Binary
      id: cached-terragrunt-binary
      uses: actions/cache@v3
      with:
        path: ${{ steps.paths.outputs.terragrunt-bin }}
        key: terragrunt-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}
    - name: Install Terragrunt
      if: steps.cached-terragrunt-binary.outputs.cache-hit != 'true'
      env:
        INSTALL_PATH: ${{ steps.paths.outputs.terragrunt-bin }}
        TERRAGRUNT_VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_ACTOR: ${{ github.actor }}
      run: |
        set -euo pipefail
        
        if [ "$TERRAGRUNT_VERSION" == "latest" ]; then
            TERRAGRUNT_URL="https://github.com/gruntwork-io/terragrunt/releases/latest/download/"
        else
            TERRAGRUNT_URL="https://github.com/gruntwork-io/terragrunt/releases/download/v$TERRAGRUNT_VERSION/"
        fi
        
        if [ "$RUNNER_OS" == "Linux" ]; then
             TERRAGRUNT_URL="$TERRAGRUNT_URL/terragrunt_linux_amd64"
             BINARY_SUFFIX=""
        elif [ "$RUNNER_OS" == "Windows" ]; then
             TERRAGRUNT_URL="$TERRAGRUNT_URL/terragrunt_windows_amd64.exe"
             BINARY_SUFFIX=".exe"
        elif [ "$RUNNER_OS" == "macOS" ]; then
             TERRAGRUNT_URL="$TERRAGRUNT_URL/terragrunt_darwin_amd64"
             BINARY_SUFFIX=""
        else
             echo "$RUNNER_OS not supported"
             exit 1
        fi
        
        curl -u "$GITHUB_ACTOR:$GITHUB_TOKEN" -Lo "$RUNNER_TEMP/terragrunt-bin/terragrunt$BINARY_SUFFIX" "$TERRAGRUNT_URL"
        chmod +x "$RUNNER_TEMP/terragrunt-bin/terragrunt$BINARY_SUFFIX"
      shell: bash
    - shell: bash
      name: Set non-interactive mode for terragrunt
      run: echo "TERRAGRUNT_NON_INTERACTIVE=true" >> "$GITHUB_ENV"
    - name: Print version
      shell: bash
      id: version
      run: |
        terragrunt --version
        echo "version=$( "$RUNNER_TEMP/terragrunt-bin/terragrunt$BINARY_SUFFIX" --version | cut -d " " -f3 | cut -c2- )" >> "$GITHUB_OUTPUT"
branding:
  icon: 'award'
  color: 'purple'

