version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: build
      include: "scope"
    ignore:
      # This currently creates a loop between the actions and the workflows.
      # Ideally they would up date but this requires a bit more thinking.
      - dependency-name: armakuni/github-actions
