tag_prefix = "v"
from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
  'perl -i -pe  "s/armakuni\/github-actions\/([a-z0-9-]+)\@v\d+\.\d+\.\d+/armakuni\/github-actions\/\$1\@v{{version}}/gm" ./.github/workflows/*.yml',
  'perl -i -pe  "s/armakuni\/github-actions\/([a-z0-9-]+)\@v\d+\.\d+\.\d+/armakuni\/github-actions\/\$1\@v{{version}}/gm" ./*/action.yml',
  'perl -i -pe  "s/armakuni\/github-actions\/([a-z0-9-]+)\@v\d+\.\d+\.\d+/armakuni\/github-actions\/\$1\@v{{version}}/gm" ./*/action.yaml'
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
# path = "CHANGELOG.md"
# template = "remote"
# remote = "github.com"
# repository = "github-actions"
# owner = "armakuni"

authors = []
