name: Check Conventional Commits
description: This Github Action ensures that all commit messages conform to the conventional commits format.

inputs:
  working-directory:
    description: The root of the git repository that you want to check.
    required: false

outputs:
  will-bump:
    value: ${{ steps.get-bump-version.outputs.bump-version != '' }}
    description: Returns 'true' when the version will bump
  bump-version:
    value: ${{ steps.get-bump-version.outputs.bump-version }}
    description: Returns 'true' when the version will bump

runs:
  using: composite
  steps:
    - uses: armakuni/github-actions/setup-cocogitto@main
      with:
        version: 5.5.0

    - name: check-commits
      run: cog check
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: get-bump-version
      run: |
        if new_version="$(cog bump --auto --dry-run)" && [[ $new_version =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
          echo "bump-version=$new_version" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
