name: Setup Poetry Action
description: Setup the Poetry on the path
inputs:
  version:
    description: Version of Poetry to install
    required: false
    default: 'latest'
outputs:
  version:
    description: The version on the path
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Setup path
      id: paths
      shell: bash
      run: |
        mkdir -p "$RUNNER_TEMP/poetry-home"
        echo "poetry-home=$RUNNER_TEMP/poetry-home" >> "$GITHUB_OUTPUT"
        echo "$RUNNER_TEMP/poetry-home/bin" >> "$GITHUB_PATH"
    - name: Discover python version
      shell: bash
      id: python-version
      run: |
        echo "python-version=$(python3 --version | cut -f2 -d' ')" >> "$GITHUB_OUTPUT"
    - name: Load cached Poetry Binary
      id: cached-poetry-binary
      uses: actions/cache@v3
      with:
        path: ${{ steps.paths.outputs.poetry-home }}
        key: poetry-${{ runner.os }}-${[ runner.arch }}-${{ steps.python-version.outputs.python-version }}-${{ inputs.version }}
    - name: Install Poetry
      if: steps.cached-poetry-binary.outputs.cache-hit != 'true'
      shell: bash
      env:
        POETRY_HOME: ${{ steps.paths.outputs.poetry-home }}
        USERS_POETRY_VERSION: ${{ inputs.version }}
      run: |
        if [ "$USERS_POETRY_VERSION" == "latest" ] ; then
          POETRY_INSTALL_SUFFIX=()
        else
          POETRY_INSTALL_SUFFIX=("--version" "$USERS_POETRY_VERSION")
        fi
        
        curl -sSL https://install.python-poetry.org | python3 - "${POETRY_INSTALL_SUFFIX[@]}"
    - name: Print version
      shell: bash
      id: version
      run: |
        poetry --version
        echo "version=$( poetry --version | cut -d '(' -f2 | cut -d " " -f2 |cut -d ")" -f1 )" >> "$GITHUB_OUTPUT"
branding:
  icon: 'award'
  color: 'purple'

