on:
  workflow_call:

jobs:
  check-conventional-commits:
    name: check-conventional-commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: check-conventional-commits
        uses: armakuni/github-actions/check-conventional-commits@v0.2.0
