# This workflow is useful for private repos but you will get more functionality
# by using Mergify for public ones.
on:
  workflow_call:
    inputs:
      merge-strategy:
        description: The strategy to use when merging the PRs (can be 'merge', 'rebase' or 'squash')
        type: string
        default: merge
      branch-protections:
        description: Decide whether to enable auto merge if branch protections exist
        type: boolean
        default: true
    
jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Enable auto-merge for Dependabot PRs
      if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
      run: gh pr merge ${{inputs.branch-protections && '--auto' || '' }} --${{ inputs.merge-strategy }} "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
