on:
  workflow_call:
    inputs:
      use-terragrunt:
        description: 'Set to "true" if you want to use Terragrunt'
        required: false
        default: false
        type: boolean
      terragrunt-version:
        description: 'The version of Terragrunt to install'
        required: false
        type: string
        default: 'latest'
      terraform-version:
        description: 'The version of Terraform to install'
        required: false
        type: string
        default: 'latest'
      working-directory:
        description: 'The path to the directory to run the lints from'
        required: false
        type: string
        default: '.'

jobs:
  lint:
    name: Lint terraform
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "$USE_TERRAGRUNT" == "true" ]] ; then
            echo "bin_name=terragrunt" >> "$GITHUB_OUTPUT"
          else
            echo "bin_name=terraform" >> "$GITHUB_OUTPUT"
          fi
        env:
          USE_TERRAGRUNT: ${{ inputs.use-terragrunt == 'true' && 'true' || 'false' }}
        shell: bash
        id: binary_name
      - uses: actions/checkout@v4
        name: Checkout
      - uses: hashicorp/setup-terraform@v2
        name: Setup Terraform
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - uses: ./../../setup-terragrunt
        if: ${{ inputs.use-terragrunt }}
        name: Setup Terragrunt
        with:
          version: ${{ inputs.terragrunt-version }}
      - name: Terraform fmt
        working-directory: ${{ inputs.working-directory }}
        run: ${{ steps.binary_name.outputs.bin_name }} fmt -check -diff -recursive
      - name: Terraform Init
        working-directory: ${{ inputs.working-directory }}
        run: ${{ steps.binary_name.outputs.bin_name }} init
      - name: Terraform Validate
        working-directory: ${{ inputs.working-directory }}
        run: ${{ steps.binary_name.outputs.bin_name }} validate
