on:
  workflow_call:

jobs:
  lint-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check workflow files
      run: |
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        ./actionlint -color
      shell: bash
