on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  test-assert-equals:
    uses: ./.github/workflows/test-assert-equals.yml

  lint-pipeline:
    uses: ./.github/workflows/lint-pipeline.yml

  test-aws-assume-oidc-role:
    # only the main branch has permissions to log into AWS
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/test-assume-aws-oidc-role.yml
    secrets:
      aws-account-id: ${{ secrets.ARMAKUNI_AWS_PROD_ACCOUNT_ID }}

  test-check-conventional-commits:
    uses: ./.github/workflows/test-check-conventional-commits.yml

  test-bump-version:
    uses: ./.github/workflows/test-bump-version.yml

  test-generate-terraform-docs:
    uses: ./.github/workflows/test-generate-terraform-docs.yml

  test-setup-cocogitto:
    uses: ./.github/workflows/test-setup-cocogitto.yml

  test-repository-details:
    uses: ./.github/workflows/test-repository-details.yml

  check-conventional-commits:
    uses: ./.github/workflows/check-conventional-commits.yml

  all-tests-succeeded:
    needs:
      - lint-pipeline
      - check-conventional-commits
      - test-assert-equals
      - test-bump-version
      - test-check-conventional-commits
      - test-generate-terraform-docs
      - test-repository-details
      - test-setup-cocogitto
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - all-tests-succeeded
      - test-aws-assume-oidc-role
    uses: ./.github/workflows/tag-and-release.yml
    secrets: inherit # automatically passes org secrets without renaming to the template
