on:
  workflow_call:

jobs:
  test-check-conventional-commits:
    name: Test check-conventional-commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: armakuni-actions

      - name: create-test-repo
        run: |
          git config --global user.email "github-actions@armakuni.com"
          git config --global user.name "AK Actions Bot"
          mkdir test-repo
          cd test-repo
          git init

      - name: create-valid-commits
        run: |
          echo "first commit" >test.txt
          git add .
          git commit -m "feat: First feature"
          echo "second commit" >test.txt
          git add .
          git commit -m "fix: Second feature"
        working-directory: test-repo

      - uses: ./armakuni-actions/check-conventional-commits
        with:
          working-directory: test-repo

      - name: create-invalid-commit
        run: |
          echo "third commit" >>test.txt
          git add .
          git commit -m "Third feature"
        working-directory: test-repo

      - id: check-failure
        name: check-conventional-commits (should fail)
        continue-on-error: true
        uses: ./armakuni-actions/check-conventional-commits
        with:
          working-directory: test-repo

      - name: confirm-failure
        uses: armakuni/github-actions/assert-equals@v0.14.4
        with:
          expected: failure
          actual: "${{ steps.check-failure.outcome }}"

  test-check-conventional-when-no-new-commits:
    name: Test check-conventional-commits when nothing to bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: armakuni-actions

      - name: create-test-repo
        run: |
          git config --global user.email "github-actions@armakuni.com"
          git config --global user.name "AK Actions Bot"
          mkdir test-repo
          cd test-repo
          git init

      - name: create-valid-commits
        run: |
          echo "first commit" >test.txt
          git add .
          git commit -m "feat: First feature"
          git tag 0.1.0
        working-directory: test-repo

      - id: check-conventional-commits
        uses: ./armakuni-actions/check-conventional-commits
        with:
          working-directory: test-repo

      - name: confirm-bump-version-is-empty
        uses: armakuni/github-actions/assert-equals@v0.14.4
        with:
          expected: 
          actual: "${{ steps.check-conventional-commits.outputs.bump-version }}"

      - name: confirm-will-bump-is-false
        uses: armakuni/github-actions/assert-equals@v0.14.4
        with:
          expected: 'false'
          actual: "${{ steps.check-conventional-commits.outputs.will-bump }}"

  test-check-conventional-when-only-non-bumping-commits:
    name: Test check-conventional-commits when nothing to bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: armakuni-actions

      - name: create-test-repo
        run: |
          git config --global user.email "github-actions@armakuni.com"
          git config --global user.name "AK Actions Bot"
          mkdir test-repo
          cd test-repo
          git init

      - name: create-valid-commits
        run: |
          echo "first commit" >test.txt
          git add .
          git commit -m "feat: First feature"
          git tag 0.1.0
          echo "second commit" >test.txt
          git add .
          git commit -m "docs: Second commit (docs will not cause a bump)"
        working-directory: test-repo

      - id: check-conventional-commits
        uses: ./armakuni-actions/check-conventional-commits
        with:
          working-directory: test-repo

      - name: confirm-bump-version-is-empty
        uses: armakuni/github-actions/assert-equals@v0.14.4
        with:
          expected: 
          actual: "${{ steps.check-conventional-commits.outputs.bump-version }}"

      - name: confirm-will-bump-is-false
        uses: armakuni/github-actions/assert-equals@v0.14.4
        with:
          expected: 'false'
          actual: "${{ steps.check-conventional-commits.outputs.will-bump }}"

  test-check-conventional-when-something-to-bump:
    name: Test check-conventional-commits when something to bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: armakuni-actions

      - name: create-test-repo
        run: |
          git config --global user.email "github-actions@armakuni.com"
          git config --global user.name "AK Actions Bot"
          mkdir test-repo
          cd test-repo
          git init

      - name: create-valid-commits
        run: |
          echo "first commit" >test.txt
          git add .
          git commit -m "feat: First feature"
          git tag 0.1.0
          echo "second commit" >test.txt
          git add .
          git commit -m "feat: First feature"
        working-directory: test-repo

      - id: check-conventional-commits
        uses: ./armakuni-actions/check-conventional-commits
        with:
          working-directory: test-repo

      - name: confirm-bump-version-is-next-semver
        uses: armakuni/github-actions/assert-equals@v0.14.4
        with:
          expected: '0.2.0'
          actual: "${{ steps.check-conventional-commits.outputs.bump-version }}"
  
      - name: confirm-will-bump-is-true
        uses: armakuni/github-actions/assert-equals@v0.14.4
        with:
          expected: 'true'
          actual: "${{ steps.check-conventional-commits.outputs.will-bump }}"
