on:
  workflow_call:
    secrets:
      aws-account-id:
        required: true

jobs:
  test-assume-aws-oidc-role:
    name: Test assume-aws-oidc-role
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: unfor19/install-aws-cli-action@v1
        with:
          arch: amd64

      - uses: ./assume-aws-oidc-role
        with:
          aws-account-id: ${{ secrets.aws-account-id }}
          aws-region: eu-west-3

      - name: check-logged-in
        run: aws sts get-caller-identity
