on:
  workflow_call:

jobs:
  test-setup-cocogitto-without-version:
    name: Test setup-cocogitto (without version)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./setup-cocogitto
      - run: cog --version

  test-setup-cocogitto-with-version:
    name: Test setup-cocogitto (with version)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./setup-cocogitto
        with:
          version: 5.0.0
      - id: cocogitto_version
        run: |
          installed_version="$(cog --version)"
          if [ "$installed_version" == "cog 5.0.0" ] ; then
            echo "Correct version installed"
          else
            echo "Incorrect version installed"
          fi
