on:
  workflow_call:

jobs:
  test-repository-details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - id: get-branch
        name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_OUTPUT"
        shell: bash

      - id: details
        uses: ./repository-details
        
      - name: check-owner
        uses: armakuni/github-actions/assert-equals@v0.17.6
        with:
          expected: "armakuni"
          actual: ${{ steps.details.outputs.owner }}

      - name: check-name
        uses: armakuni/github-actions/assert-equals@v0.17.6
        with:
          expected: "github-actions"
          actual: "${{ steps.details.outputs.name }}"

      - name: check-branch
        uses: armakuni/github-actions/assert-equals@v0.17.6
        with:
          expected: "${{ steps.get-branch.outputs.branch }}"
          actual: "${{ steps.details.outputs.branch }}"
