on:
  workflow_call:

jobs:
  test-generate-terraform-docs-without-artifacts:
    name: Test generate-terraform-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./generate-terraform-docs
        with:
          working-directory: generate-terraform-docs/example
          output-file: README.md

      - name: Check generated docs
        run: grep "The name of the bucket to create" README.md
        working-directory: generate-terraform-docs/example

  test-generate-terraform-docs-with-artifacts:
    name: Test generate-terraform-docs (with artifact-name)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./generate-terraform-docs
        with:
          working-directory: generate-terraform-docs/example
          output-file: README.md
          artifact-name: generated-docs

  test-artifact-was-uploaded:
    name: Test artifact uploaded
    runs-on: ubuntu-latest
    needs:
      - test-generate-terraform-docs-with-artifacts
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - run: ls -la

      - name: Check generated docs
        run: grep "The name of the bucket to create" generated-docs/README.md
